# -*- makefile -*-
#----------------------------------------------------------------------------
#       GNU ACE Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/ltzd/ACE_wrappers643/bin/mwc.pl -type gnuace -include /home/ltzd/Terabit -global /home/ltzd/Terabit/linaio.mpb aio.mwc
#
#----------------------------------------------------------------------------

MAKEFILE = GNUmakefile

ifeq ($(findstring k,$(MAKEFLAGS)),k)
  KEEP_GOING = -
endif

include $(ACE_ROOT)/include/makeinclude/macros.GNU

all: TProactor-target TProactor_SSL IOTerabit IOTerabit_SSL ex0 ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex7a ex8 F2_Test F_Test P2_Test PAUL_SSL_Test Web_Test PM_Test PN_Test PSSL_Test P3_Test P1_Test P_Test R_Test TM_Test TSSL_Test T_Test Timer_Test U_Logger U_Test TestList TestMon TestProdCons
# all: TProactor-target TProactor_SSL IOTerabit IOTerabit_SSL


depend: TProactor-target-depend TProactor_SSL-depend IOTerabit-depend IOTerabit_SSL-depend ex0-depend ex1-depend ex2-depend ex3-depend ex4-depend ex5-depend ex6-depend ex7-depend ex7a-depend ex8-depend F2_Test-depend F_Test-depend P2_Test-depend PAUL_SSL_Test-depend Web_Test-depend PM_Test-depend PN_Test-depend PSSL_Test-depend P3_Test-depend P1_Test-depend P_Test-depend R_Test-depend TM_Test-depend TSSL_Test-depend T_Test-depend Timer_Test-depend U_Logger-depend U_Test-depend TestList-depend TestMon-depend TestProdCons-depend
# depend: TProactor-target-depend TProactor_SSL-depend IOTerabit-depend IOTerabit_SSL-depend


REMAINING_TARGETS := $(filter-out all depend,$(TARGETS_NESTED:.nested=)) $(CUSTOM_TARGETS)

$(REMAINING_TARGETS):
	$(KEEP_GOING)@cd TProactor && $(MAKE) -f GNUmakefile.TProactor $(@)
	$(KEEP_GOING)@cd TProactor/SSL && $(MAKE) -f GNUmakefile.TProactor_SSL $(@)
	$(KEEP_GOING)@cd app/IOTerabit && $(MAKE) -f GNUmakefile.IOTerabit $(@)
	$(KEEP_GOING)@cd app/IOTerabit/SSL && $(MAKE) -f GNUmakefile.IOTerabit_SSL $(@)
	$(KEEP_GOING)@cd app/examples/ex0 && $(MAKE) -f GNUmakefile.ex0 $(@)
	$(KEEP_GOING)@cd app/examples/ex1 && $(MAKE) -f GNUmakefile.ex1 $(@)
	$(KEEP_GOING)@cd app/examples/ex2 && $(MAKE) -f GNUmakefile.ex2 $(@)
	$(KEEP_GOING)@cd app/examples/ex3 && $(MAKE) -f GNUmakefile.ex3 $(@)
	$(KEEP_GOING)@cd app/examples/ex4 && $(MAKE) -f GNUmakefile.ex4 $(@)
	$(KEEP_GOING)@cd app/examples/ex5 && $(MAKE) -f GNUmakefile.ex5 $(@)
	$(KEEP_GOING)@cd app/examples/ex6 && $(MAKE) -f GNUmakefile.ex6 $(@)
	$(KEEP_GOING)@cd app/examples/ex7 && $(MAKE) -f GNUmakefile.ex7 $(@)
	$(KEEP_GOING)@cd app/examples/ex7a && $(MAKE) -f GNUmakefile.ex7a $(@)
	$(KEEP_GOING)@cd app/examples/ex8 && $(MAKE) -f GNUmakefile.ex8 $(@)
	$(KEEP_GOING)@cd tests/F2_Test && $(MAKE) -f GNUmakefile.F2_Test $(@)
	$(KEEP_GOING)@cd tests/F_Test && $(MAKE) -f GNUmakefile.F_Test $(@)
	$(KEEP_GOING)@cd tests/P2_Test && $(MAKE) -f GNUmakefile.P2_Test $(@)
	$(KEEP_GOING)@cd tests/PAUL_SSL_Test && $(MAKE) -f GNUmakefile.PAUL_SSL_Test $(@)
	$(KEEP_GOING)@cd tests/PM_Test && $(MAKE) -f GNUmakefile.Web_Test $(@)
	$(KEEP_GOING)@cd tests/PM_Test && $(MAKE) -f GNUmakefile.PM_Test $(@)
	$(KEEP_GOING)@cd tests/PN_Test && $(MAKE) -f GNUmakefile.PN_Test $(@)
	$(KEEP_GOING)@cd tests/PSSL_Test && $(MAKE) -f GNUmakefile.PSSL_Test $(@)
	$(KEEP_GOING)@cd tests/P_Test && $(MAKE) -f GNUmakefile.P3_Test $(@)
	$(KEEP_GOING)@cd tests/P_Test && $(MAKE) -f GNUmakefile.P1_Test $(@)
	$(KEEP_GOING)@cd tests/P_Test && $(MAKE) -f GNUmakefile.P_Test $(@)
	$(KEEP_GOING)@cd tests/R_Test && $(MAKE) -f GNUmakefile.R_Test $(@)
	$(KEEP_GOING)@cd tests/TM_Test && $(MAKE) -f GNUmakefile.TM_Test $(@)
	$(KEEP_GOING)@cd tests/TSSL_Test && $(MAKE) -f GNUmakefile.TSSL_Test $(@)
	$(KEEP_GOING)@cd tests/T_Test && $(MAKE) -f GNUmakefile.T_Test $(@)
	$(KEEP_GOING)@cd tests/Timer_Test && $(MAKE) -f GNUmakefile.Timer_Test $(@)
	$(KEEP_GOING)@cd tests/U_Logger && $(MAKE) -f GNUmakefile.U_Logger $(@)
	$(KEEP_GOING)@cd tests/U_Test && $(MAKE) -f GNUmakefile.U_Test $(@)
	$(KEEP_GOING)@cd tests/misc && $(MAKE) -f GNUmakefile.TestList $(@)
	$(KEEP_GOING)@cd tests/misc && $(MAKE) -f GNUmakefile.TestMon $(@)
	$(KEEP_GOING)@cd tests/misc && $(MAKE) -f GNUmakefile.TestProdCons $(@)

.PHONY: TProactor-target
TProactor-target:
	$(KEEP_GOING)@cd TProactor && $(MAKE) -f GNUmakefile.TProactor all

.PHONY: TProactor-target-depend
TProactor-target-depend:
	$(KEEP_GOING)@cd TProactor && $(MAKE) -f GNUmakefile.TProactor depend

.PHONY: TProactor_SSL
TProactor_SSL: TProactor-target
	$(KEEP_GOING)@cd TProactor/SSL && $(MAKE) -f GNUmakefile.TProactor_SSL all

.PHONY: TProactor_SSL-depend
TProactor_SSL-depend:
	$(KEEP_GOING)@cd TProactor/SSL && $(MAKE) -f GNUmakefile.TProactor_SSL depend

.PHONY: IOTerabit
IOTerabit: TProactor-target
	$(KEEP_GOING)@cd app/IOTerabit && $(MAKE) -f GNUmakefile.IOTerabit all

.PHONY: IOTerabit-depend
IOTerabit-depend:
	$(KEEP_GOING)@cd app/IOTerabit && $(MAKE) -f GNUmakefile.IOTerabit depend

.PHONY: IOTerabit_SSL
IOTerabit_SSL: TProactor-target TProactor_SSL IOTerabit
	$(KEEP_GOING)@cd app/IOTerabit/SSL && $(MAKE) -f GNUmakefile.IOTerabit_SSL all

.PHONY: IOTerabit_SSL-depend
IOTerabit_SSL-depend:
	$(KEEP_GOING)@cd app/IOTerabit/SSL && $(MAKE) -f GNUmakefile.IOTerabit_SSL depend

.PHONY: ex0
ex0: TProactor-target IOTerabit
	$(KEEP_GOING)@cd app/examples/ex0 && $(MAKE) -f GNUmakefile.ex0 all

.PHONY: ex0-depend
ex0-depend:
	$(KEEP_GOING)@cd app/examples/ex0 && $(MAKE) -f GNUmakefile.ex0 depend

.PHONY: ex1
ex1: TProactor-target IOTerabit
	$(KEEP_GOING)@cd app/examples/ex1 && $(MAKE) -f GNUmakefile.ex1 all

.PHONY: ex1-depend
ex1-depend:
	$(KEEP_GOING)@cd app/examples/ex1 && $(MAKE) -f GNUmakefile.ex1 depend

.PHONY: ex2
ex2: TProactor-target IOTerabit
	$(KEEP_GOING)@cd app/examples/ex2 && $(MAKE) -f GNUmakefile.ex2 all

.PHONY: ex2-depend
ex2-depend:
	$(KEEP_GOING)@cd app/examples/ex2 && $(MAKE) -f GNUmakefile.ex2 depend

.PHONY: ex3
ex3: TProactor-target IOTerabit
	$(KEEP_GOING)@cd app/examples/ex3 && $(MAKE) -f GNUmakefile.ex3 all

.PHONY: ex3-depend
ex3-depend:
	$(KEEP_GOING)@cd app/examples/ex3 && $(MAKE) -f GNUmakefile.ex3 depend

.PHONY: ex4
ex4: TProactor-target IOTerabit
	$(KEEP_GOING)@cd app/examples/ex4 && $(MAKE) -f GNUmakefile.ex4 all

.PHONY: ex4-depend
ex4-depend:
	$(KEEP_GOING)@cd app/examples/ex4 && $(MAKE) -f GNUmakefile.ex4 depend

.PHONY: ex5
ex5: TProactor-target IOTerabit
	$(KEEP_GOING)@cd app/examples/ex5 && $(MAKE) -f GNUmakefile.ex5 all

.PHONY: ex5-depend
ex5-depend:
	$(KEEP_GOING)@cd app/examples/ex5 && $(MAKE) -f GNUmakefile.ex5 depend

.PHONY: ex6
ex6: TProactor-target IOTerabit
	$(KEEP_GOING)@cd app/examples/ex6 && $(MAKE) -f GNUmakefile.ex6 all

.PHONY: ex6-depend
ex6-depend:
	$(KEEP_GOING)@cd app/examples/ex6 && $(MAKE) -f GNUmakefile.ex6 depend

.PHONY: ex7
ex7: TProactor-target IOTerabit
	$(KEEP_GOING)@cd app/examples/ex7 && $(MAKE) -f GNUmakefile.ex7 all

.PHONY: ex7-depend
ex7-depend:
	$(KEEP_GOING)@cd app/examples/ex7 && $(MAKE) -f GNUmakefile.ex7 depend

.PHONY: ex7a
ex7a: TProactor-target IOTerabit
	$(KEEP_GOING)@cd app/examples/ex7a && $(MAKE) -f GNUmakefile.ex7a all

.PHONY: ex7a-depend
ex7a-depend:
	$(KEEP_GOING)@cd app/examples/ex7a && $(MAKE) -f GNUmakefile.ex7a depend

.PHONY: ex8
ex8: TProactor-target TProactor_SSL IOTerabit IOTerabit_SSL
	$(KEEP_GOING)@cd app/examples/ex8 && $(MAKE) -f GNUmakefile.ex8 all

.PHONY: ex8-depend
ex8-depend:
	$(KEEP_GOING)@cd app/examples/ex8 && $(MAKE) -f GNUmakefile.ex8 depend

.PHONY: F2_Test
F2_Test: TProactor-target
	$(KEEP_GOING)@cd tests/F2_Test && $(MAKE) -f GNUmakefile.F2_Test all

.PHONY: F2_Test-depend
F2_Test-depend:
	$(KEEP_GOING)@cd tests/F2_Test && $(MAKE) -f GNUmakefile.F2_Test depend

.PHONY: F_Test
F_Test: TProactor-target
	$(KEEP_GOING)@cd tests/F_Test && $(MAKE) -f GNUmakefile.F_Test all

.PHONY: F_Test-depend
F_Test-depend:
	$(KEEP_GOING)@cd tests/F_Test && $(MAKE) -f GNUmakefile.F_Test depend

.PHONY: P2_Test
P2_Test: TProactor-target
	$(KEEP_GOING)@cd tests/P2_Test && $(MAKE) -f GNUmakefile.P2_Test all

.PHONY: P2_Test-depend
P2_Test-depend:
	$(KEEP_GOING)@cd tests/P2_Test && $(MAKE) -f GNUmakefile.P2_Test depend

.PHONY: PAUL_SSL_Test
PAUL_SSL_Test: TProactor-target TProactor_SSL
	$(KEEP_GOING)@cd tests/PAUL_SSL_Test && $(MAKE) -f GNUmakefile.PAUL_SSL_Test all

.PHONY: PAUL_SSL_Test-depend
PAUL_SSL_Test-depend:
	$(KEEP_GOING)@cd tests/PAUL_SSL_Test && $(MAKE) -f GNUmakefile.PAUL_SSL_Test depend

.PHONY: Web_Test
Web_Test: TProactor-target TProactor_SSL
	$(KEEP_GOING)@cd tests/PM_Test && $(MAKE) -f GNUmakefile.Web_Test all

.PHONY: Web_Test-depend
Web_Test-depend:
	$(KEEP_GOING)@cd tests/PM_Test && $(MAKE) -f GNUmakefile.Web_Test depend

.PHONY: PM_Test
PM_Test: TProactor-target Web_Test
	$(KEEP_GOING)@cd tests/PM_Test && $(MAKE) -f GNUmakefile.PM_Test all

.PHONY: PM_Test-depend
PM_Test-depend:
	$(KEEP_GOING)@cd tests/PM_Test && $(MAKE) -f GNUmakefile.PM_Test depend

.PHONY: PN_Test
PN_Test: TProactor-target
	$(KEEP_GOING)@cd tests/PN_Test && $(MAKE) -f GNUmakefile.PN_Test all

.PHONY: PN_Test-depend
PN_Test-depend:
	$(KEEP_GOING)@cd tests/PN_Test && $(MAKE) -f GNUmakefile.PN_Test depend

.PHONY: PSSL_Test
PSSL_Test: TProactor-target TProactor_SSL
	$(KEEP_GOING)@cd tests/PSSL_Test && $(MAKE) -f GNUmakefile.PSSL_Test all

.PHONY: PSSL_Test-depend
PSSL_Test-depend:
	$(KEEP_GOING)@cd tests/PSSL_Test && $(MAKE) -f GNUmakefile.PSSL_Test depend

.PHONY: P3_Test
P3_Test: TProactor-target
	$(KEEP_GOING)@cd tests/P_Test && $(MAKE) -f GNUmakefile.P3_Test all

.PHONY: P3_Test-depend
P3_Test-depend:
	$(KEEP_GOING)@cd tests/P_Test && $(MAKE) -f GNUmakefile.P3_Test depend

.PHONY: P1_Test
P1_Test: TProactor-target P3_Test
	$(KEEP_GOING)@cd tests/P_Test && $(MAKE) -f GNUmakefile.P1_Test all

.PHONY: P1_Test-depend
P1_Test-depend:
	$(KEEP_GOING)@cd tests/P_Test && $(MAKE) -f GNUmakefile.P1_Test depend

.PHONY: P_Test
P_Test: TProactor-target P3_Test
	$(KEEP_GOING)@cd tests/P_Test && $(MAKE) -f GNUmakefile.P_Test all

.PHONY: P_Test-depend
P_Test-depend:
	$(KEEP_GOING)@cd tests/P_Test && $(MAKE) -f GNUmakefile.P_Test depend

.PHONY: R_Test
R_Test: TProactor-target
	$(KEEP_GOING)@cd tests/R_Test && $(MAKE) -f GNUmakefile.R_Test all

.PHONY: R_Test-depend
R_Test-depend:
	$(KEEP_GOING)@cd tests/R_Test && $(MAKE) -f GNUmakefile.R_Test depend

.PHONY: TM_Test
TM_Test: TProactor-target
	$(KEEP_GOING)@cd tests/TM_Test && $(MAKE) -f GNUmakefile.TM_Test all

.PHONY: TM_Test-depend
TM_Test-depend:
	$(KEEP_GOING)@cd tests/TM_Test && $(MAKE) -f GNUmakefile.TM_Test depend

.PHONY: TSSL_Test
TSSL_Test: TProactor-target TProactor_SSL
	$(KEEP_GOING)@cd tests/TSSL_Test && $(MAKE) -f GNUmakefile.TSSL_Test all

.PHONY: TSSL_Test-depend
TSSL_Test-depend:
	$(KEEP_GOING)@cd tests/TSSL_Test && $(MAKE) -f GNUmakefile.TSSL_Test depend

.PHONY: T_Test
T_Test: TProactor-target
	$(KEEP_GOING)@cd tests/T_Test && $(MAKE) -f GNUmakefile.T_Test all

.PHONY: T_Test-depend
T_Test-depend:
	$(KEEP_GOING)@cd tests/T_Test && $(MAKE) -f GNUmakefile.T_Test depend

.PHONY: Timer_Test
Timer_Test: TProactor-target
	$(KEEP_GOING)@cd tests/Timer_Test && $(MAKE) -f GNUmakefile.Timer_Test all

.PHONY: Timer_Test-depend
Timer_Test-depend:
	$(KEEP_GOING)@cd tests/Timer_Test && $(MAKE) -f GNUmakefile.Timer_Test depend

.PHONY: U_Logger
U_Logger: TProactor-target
	$(KEEP_GOING)@cd tests/U_Logger && $(MAKE) -f GNUmakefile.U_Logger all

.PHONY: U_Logger-depend
U_Logger-depend:
	$(KEEP_GOING)@cd tests/U_Logger && $(MAKE) -f GNUmakefile.U_Logger depend

.PHONY: U_Test
U_Test: TProactor-target
	$(KEEP_GOING)@cd tests/U_Test && $(MAKE) -f GNUmakefile.U_Test all

.PHONY: U_Test-depend
U_Test-depend:
	$(KEEP_GOING)@cd tests/U_Test && $(MAKE) -f GNUmakefile.U_Test depend

.PHONY: TestList
TestList:
	$(KEEP_GOING)@cd tests/misc && $(MAKE) -f GNUmakefile.TestList all

.PHONY: TestList-depend
TestList-depend:
	$(KEEP_GOING)@cd tests/misc && $(MAKE) -f GNUmakefile.TestList depend

.PHONY: TestMon
TestMon:
	$(KEEP_GOING)@cd tests/misc && $(MAKE) -f GNUmakefile.TestMon all

.PHONY: TestMon-depend
TestMon-depend:
	$(KEEP_GOING)@cd tests/misc && $(MAKE) -f GNUmakefile.TestMon depend

.PHONY: TestProdCons
TestProdCons:
	$(KEEP_GOING)@cd tests/misc && $(MAKE) -f GNUmakefile.TestProdCons all

.PHONY: TestProdCons-depend
TestProdCons-depend:
	$(KEEP_GOING)@cd tests/misc && $(MAKE) -f GNUmakefile.TestProdCons depend

project_name_list:
	@echo TProactor-target
	@echo TProactor_SSL
	@echo IOTerabit
	@echo IOTerabit_SSL
	@echo ex0
	@echo ex1
	@echo ex2
	@echo ex3
	@echo ex4
	@echo ex5
	@echo ex6
	@echo ex7
	@echo ex7a
	@echo ex8
	@echo F2_Test
	@echo F_Test
	@echo P2_Test
	@echo PAUL_SSL_Test
	@echo PM_Test
	@echo Web_Test
	@echo PN_Test
	@echo PSSL_Test
	@echo P1_Test
	@echo P3_Test
	@echo P_Test
	@echo R_Test
	@echo TM_Test
	@echo TSSL_Test
	@echo T_Test
	@echo Timer_Test
	@echo U_Logger
	@echo U_Test
	@echo TestList
	@echo TestMon
	@echo TestProdCons
